version: 0.2

phases:
  build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 609374022227.dkr.ecr.us-east-1.amazonaws.com/narcade
      - ./gradlew assembleDebug
artifacts:
  files:
    - app/build/outputs/apk/app-debug.apk
